version: 2
jobs:
  build-linux:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/setup-rngd.sh
      - run: docker build -f Dockerfile.sdk.base -t orbs:base-sdk .
      - run: docker build -f Dockerfile.sdk -t orbs:sdk .
      - run: ./circleci/export.sh

workflows:
  version: 2
  build:
    jobs:
      - build-linux
