version: 2
jobs:
  build-server:
    machine: true
    steps:
      - checkout
      - run: ./docker/build-server-base.sh
      - run: ./docker-build.sh
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: docker push ${DOCKER_IMAGE}
      - store_artifacts:
          path: logs

  build-sdk:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/setup-rngd.sh
      - run: ./docker/build-sdk-base.sh
      - run: ./docker/build-sdk.sh
      - store_artifacts:
          path: logs

  build-bot:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/setup-rngd.sh
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: ./docker/build-sdk-base.sh
      - run: ./docker/build-bot.sh
      - run: export DOCKER_TAG=$(./docker-tag.sh) && docker tag orbs:bot ${DOCKER_IMAGE_BOT}:${DOCKER_TAG}
      - run: docker push ${DOCKER_IMAGE_BOT}

  deploy:
    machine: true
    steps:
      - checkout
      - run: echo LOGZIO_API_KEY=$LOGZIO_API_KEY >> deploy/bootstrap/.env-secrets
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: ./.circleci/docker-pull.sh
      - run: ./.circleci/deploy.sh

  e2e:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/setup-rngd.sh
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: ./.circleci/docker-pull.sh
      - run: ./docker/build-sdk-base.sh
      - run: ./docker/build-e2e.sh
      - run: ./docker-test.sh

  success:
    machine: true
    steps:
      - run: echo "Success!"

  e2e-testnet:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/setup-rngd.sh
      - run: $(aws ecr get-login --no-include-email --region us-west-2)
      - run: ./docker/build-sdk-base.sh
      - run: ./docker/build-e2e.sh
      - run: ./.circleci/e2e-testnet.sh

workflows:
  version: 2
  build:
    jobs:
      - build-sdk
      - build-server
      - build-bot
      - e2e:
          requires:
            - build-server
      - success:
          requires:
            - build-sdk
            - e2e
            - build-bot
      - deploy:
          requires:
            - success
          filters:
            branches:
              only: master
      - e2e-testnet:
          requires:
            - deploy
          filters:
            branches:
              only: master
