version: 2
jobs:
  build-linux:
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - run: ./.circleci/setup-cmake.sh
      - run: ./.circleci/setup-rngd.sh
      - run: ./build.sh

workflows:
  version: 2
  build:
    jobs:
      - build-linux
