version: 2
jobs:
  build-linux:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: ./.circleci/setup-rngd.sh
      - run: ./.circleci/setup-sdk.sh && ./build.sh

workflows:
  version: 2
  build:
    jobs:
      - build-linux
